# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mac_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(974, 399)
        self.pushButton_macEkle = QtWidgets.QPushButton(Form)
        self.pushButton_macEkle.setGeometry(QtCore.QRect(250, 280, 93, 28))
        self.pushButton_macEkle.setObjectName("pushButton_macEkle")
        self.pushButton_macSil = QtWidgets.QPushButton(Form)
        self.pushButton_macSil.setGeometry(QtCore.QRect(370, 280, 93, 28))
        self.pushButton_macSil.setObjectName("pushButton_macSil")
        self.pushButton_macDuzenle = QtWidgets.QPushButton(Form)
        self.pushButton_macDuzenle.setGeometry(QtCore.QRect(480, 280, 93, 28))
        self.pushButton_macDuzenle.setObjectName("pushButton_macDuzenle")
        self.pushButton_macListele = QtWidgets.QPushButton(Form)
        self.pushButton_macListele.setGeometry(QtCore.QRect(600, 280, 93, 28))
        self.pushButton_macListele.setObjectName("pushButton_macListele")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(320, 30, 461, 221))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 70, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 71, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_takim1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_takim1.setGeometry(QtCore.QRect(130, 70, 113, 22))
        self.lineEdit_takim1.setObjectName("lineEdit_takim1")
        self.lineEdit_takim2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_takim2.setGeometry(QtCore.QRect(130, 110, 113, 22))
        self.lineEdit_takim2.setObjectName("lineEdit_takim2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 320, 131, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_duzenelencekmacid = QtWidgets.QLineEdit(Form)
        self.lineEdit_duzenelencekmacid.setGeometry(QtCore.QRect(40, 350, 113, 22))
        self.lineEdit_duzenelencekmacid.setObjectName("lineEdit_duzenelencekmacid")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_macEkle.setText(_translate("Form", "Maç Ekle"))
        self.pushButton_macSil.setText(_translate("Form", "Maç Sil"))
        self.pushButton_macDuzenle.setText(_translate("Form", "Maç Düzenle"))
        self.pushButton_macListele.setText(_translate("Form", "Maç listele"))
        self.label.setText(_translate("Form", "Takım1 id"))
        self.label_2.setText(_translate("Form", "Takım2 id"))
        self.label_3.setText(_translate("Form", "Düzenlenecek Maç ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
