# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teknik_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(901, 415)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 131, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEdit_adi = QtWidgets.QLineEdit(Form)
        self.lineEdit_adi.setGeometry(QtCore.QRect(190, 80, 113, 22))
        self.lineEdit_adi.setObjectName("lineEdit_adi")
        self.lineEdit_kupasayisi = QtWidgets.QLineEdit(Form)
        self.lineEdit_kupasayisi.setGeometry(QtCore.QRect(190, 140, 113, 22))
        self.lineEdit_kupasayisi.setObjectName("lineEdit_kupasayisi")
        self.lineEdit_takimid = QtWidgets.QLineEdit(Form)
        self.lineEdit_takimid.setGeometry(QtCore.QRect(190, 210, 113, 22))
        self.lineEdit_takimid.setObjectName("lineEdit_takimid")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(357, 50, 521, 192))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(240, 280, 151, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 280, 141, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(570, 280, 141, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(730, 280, 151, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(60, 320, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(180, 320, 231, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(440, 320, 161, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(640, 320, 81, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_teknikid = QtWidgets.QLineEdit(Form)
        self.lineEdit_teknikid.setGeometry(QtCore.QRect(180, 350, 221, 22))
        self.lineEdit_teknikid.setObjectName("lineEdit_teknikid")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(440, 350, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_yenideger = QtWidgets.QLineEdit(Form)
        self.lineEdit_yenideger.setGeometry(QtCore.QRect(620, 350, 121, 22))
        self.lineEdit_yenideger.setObjectName("lineEdit_yenideger")

        self.retranslateUi(Form)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Adı"))
        self.label_2.setText(_translate("Form", "Kazandığı Kupa Sayısı"))
        self.label_3.setText(_translate("Form", "Takım id"))
        self.pushButton.setText(_translate("Form", "Teknik Direktör Ekle"))
        self.pushButton_2.setText(_translate("Form", "Teknik Direktör Sil"))
        self.pushButton_3.setText(_translate("Form", "Teknik Direktör Listele"))
        self.pushButton_4.setText(_translate("Form", "Teknik Direktör Düzenle"))
        self.label_4.setText(_translate("Form", "Düzenleme"))
        self.label_5.setText(_translate("Form", "Düzenlemek istenilen teknik direktör id "))
        self.label_6.setText(_translate("Form", "Düzenlemek istenen kolon"))
        self.label_7.setText(_translate("Form", "yeni değer"))
        self.comboBox.setItemText(0, _translate("Form", "Adı"))
        self.comboBox.setItemText(1, _translate("Form", "Kazandığı Kupa Sayısı"))
        self.comboBox.setItemText(2, _translate("Form", "Takım id"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
